### ISSUE TITLE
Sort out the panics.

### ISSUE THREAD

**Issue by Ticki** [redox-os/sodium#37]
Sodium currently are quite prone to panics. If you encounter a panic, add it here.

**Comment by LordPython** [comment]
Executing `0g` causes the following panic:
```
Starting Sodium
First redraw of the screen
thread 'main' panicked at 'attempt to subtract with overflow', src/core/exec.rs:148
stack backtrace:
   0:        0x10c12c4f3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h7b906ec435ded35c
   1:        0x10c12db54 - std::panicking::default_hook::{{closure}}::h44d92332f38028b9
   2:        0x10c12d76d - std::panicking::default_hook::ha8486ead32221b33
   3:        0x10c1301f7 - std::panicking::rust_panic_with_hook::hdbc3bba6a9dc0bb9
   4:        0x10c130094 - std::panicking::begin_panic::ha249c774b9bf96e1
   5:        0x10c130002 - std::panicking::begin_panic_fmt::ha197daaf02a649ab
   6:        0x10c12ff67 - rust_begin_unwind
   7:        0x10c151190 - core::panicking::panic_fmt::h7414cb5ce71ea361
   8:        0x10c151094 - core::panicking::panic::hcbe9ad6a1a4f4afd
   9:        0x10c0fe58a - sodium::core::exec::<impl sodium::state::editor::Editor>::exec::h36fffba4df15a2ce
  10:        0x10c10af6a - sodium::state::editor::Editor::init::hbcafe5e553573e00
  11:        0x10c10bd9c - sodium::main::h2fe1cb1d57b9da00
  12:        0x10c12ff25 - std::panicking::try::do_call::h24a2756282b9a31c
  13:        0x10c130c4a - __rust_maybe_catch_panic
  14:        0x10c1304b6 - std::rt::lang_start::hd19f94db0c6a490e
  15:        0x10c10c459 - main
```

**Comment by LordPython** [comment]
Executing `b`, `alt-space`, `shift-b` causes the following:
```
Starting Sodium
First redraw of the screen
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
stack backtrace:
   0:        0x10c55d4f3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h7b906ec435ded35c
   1:        0x10c55eb54 - std::panicking::default_hook::{{closure}}::h44d92332f38028b9
   2:        0x10c55e76d - std::panicking::default_hook::ha8486ead32221b33
   3:        0x10c5611f7 - std::panicking::rust_panic_with_hook::hdbc3bba6a9dc0bb9
   4:        0x10c561094 - std::panicking::begin_panic::ha249c774b9bf96e1
   5:        0x10c561002 - std::panicking::begin_panic_fmt::ha197daaf02a649ab
   6:        0x10c560f67 - rust_begin_unwind
   7:        0x10c582190 - core::panicking::panic_fmt::h7414cb5ce71ea361
   8:        0x10c582094 - core::panicking::panic::hcbe9ad6a1a4f4afd
   9:        0x10c517b7c - <core::option::Option<T>>::unwrap::h2a5b725555cb4c08
  10:        0x10c53c43c - sodium::state::cursor::<impl sodium::state::editor::Editor>::cursor::hdb997da0368b8d6e
  11:        0x10c52eff5 - sodium::core::exec::<impl sodium::state::editor::Editor>::exec::h36fffba4df15a2ce
  12:        0x10c53bf6a - sodium::state::editor::Editor::init::hbcafe5e553573e00
  13:        0x10c53cd9c - sodium::main::h2fe1cb1d57b9da00
  14:        0x10c560f25 - std::panicking::try::do_call::h24a2756282b9a31c
  15:        0x10c561c4a - __rust_maybe_catch_panic
  16:        0x10c5614b6 - std::rt::lang_start::hd19f94db0c6a490e
  17:        0x10c53d459 - main
```

**Comment by sketchet** [comment]
Executing `dL` on any line except line 1 panics with the following:
```
thread 'main' panicked at 'Out of bound', src/edit/buffer.rs:183
stack backtrace:
   0:     0x55dd7072bd83 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h0c49f46a3545f908
   1:     0x55dd707281d4 - std::sys_common::backtrace::_print::hcef39a9816714c4c
   2:     0x55dd7072d6c7 - std::panicking::default_hook::{{closure}}::h7c3c94835e02f846
   3:     0x55dd7072d24b - std::panicking::default_hook::h0bf7bc3112fb107d
   4:     0x55dd7072dadb - std::panicking::rust_panic_with_hook::ha27630c950090fec
   5:     0x55dd706e62f8 - std::panicking::begin_panic::hd180c5239c4f5cb8
   6:     0x55dd70700ecf - <sodium::edit::buffer::SplitBuffer as sodium::edit::buffer::TextBuffer<'a>>::focus_hint_y::h6b894952357078c1
   7:     0x55dd707071fe - sodium::state::editor::Editor::hint::h36c183e0c48e14ed
   8:     0x55dd70702c64 - sodium::edit::selection::<impl sodium::state::editor::Editor>::remove_rb::hfcaac6f83267cd3a
   9:     0x55dd706f99da - sodium::core::exec::<impl sodium::state::editor::Editor>::exec::h2add5126c3ffaca6
  10:     0x55dd70706ee5 - sodium::state::editor::Editor::init::h9e3d6d01915782b2
  11:     0x55dd70707d0c - sodium::main::h7c9b41d2342d2dda
  12:     0x55dd7072d835 - std::panicking::try::do_call::h689a21caeeef92aa
  13:     0x55dd7073438a - __rust_maybe_catch_panic
  14:     0x55dd7072e01a - std::rt::lang_start::hf63d494cb7dd034c
  15:     0x55dd70708382 - main
  16:     0x7f8c16d2a510 - __libc_start_main
  17:     0x55dd706ddd49 - _start
  18:                0x0 - <unknown>
```

**Comment by chenshuiluke** [comment]
Pressing any key gives me:

	Starting Sodium
	First redraw of the screen
	thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:329
	stack backtrace:
	   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
		     at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
	   1: std::sys_common::backtrace::_print
		     at /checkout/src/libstd/sys_common/backtrace.rs:71
	   2: std::panicking::default_hook::{{closure}}
		     at /checkout/src/libstd/sys_common/backtrace.rs:60
		     at /checkout/src/libstd/panicking.rs:355
	   3: std::panicking::default_hook
		     at /checkout/src/libstd/panicking.rs:371
	   4: std::panicking::rust_panic_with_hook
		     at /checkout/src/libstd/panicking.rs:549
	   5: std::panicking::begin_panic
		     at /checkout/src/libstd/panicking.rs:511
	   6: std::panicking::begin_panic_fmt
		     at /checkout/src/libstd/panicking.rs:495
	   7: rust_begin_unwind
		     at /checkout/src/libstd/panicking.rs:471
	   8: core::panicking::panic_fmt
		     at /checkout/src/libcore/panicking.rs:69
	   9: core::panicking::panic
		     at /checkout/src/libcore/panicking.rs:49
	  10: <core::option::Option<T>>::unwrap
		     at /checkout/src/libcore/macros.rs:21
	  11: sdl2::event::Event::from_ll
		     at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-0.9.1/src/sdl2/event.rs:644
	  12: sdl2::event::wait_event
		     at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-0.9.1/src/sdl2/event.rs:992
	  13: sdl2::event::<impl sdl2::sdl::EventPump>::wait_event
		     at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-0.9.1/src/sdl2/event.rs:1062
	  14: orbclient::imp::window::Window::events
		     at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/orbclient-0.1.26/src/sdl2/window.rs:469
	  15: sodium::io::parse::<impl sodium::state::editor::Editor>::get_inst
		     at ./src/io/parse.rs:72
	  16: sodium::state::editor::Editor::init
		     at ./src/state/editor.rs:293
	  17: sodium::main
		     at ./src/main.rs:24
	  18: __rust_maybe_catch_panic
		     at /checkout/src/libpanic_unwind/lib.rs:98
	  19: std::rt::lang_start
		     at /checkout/src/libstd/panicking.rs:433
		     at /checkout/src/libstd/panic.rs:361
		     at /checkout/src/libstd/rt.rs:57
	  20: main
	  21: __libc_start_main
	  22: _start

**Comment by difarem** [comment]
Saving an empty buffer without a specified filename:
```
Starting Sodium
First redraw of the screen
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /checkout/src/liballoc/vec.rs:1551:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at /checkout/src/libcore/panicking.rs:58
  10: <alloc::vec::Vec<T> as core::ops::index::Index<usize>>::index
             at /checkout/src/liballoc/vec.rs:1551
  11: sodium::io::file::<impl sodium::state::editor::Editor>::write
             at src/io/file.rs:60
  12: sodium::core::prompt::<impl sodium::state::editor::Editor>::invoke
             at src/core/prompt.rs:144
  13: sodium::core::exec::<impl sodium::state::editor::Editor>::exec
             at src/core/exec.rs:279
  14: sodium::state::editor::Editor::init
             at src/state/editor.rs:320
  15: sodium::main
             at src/main.rs:24
  16: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  17: std::panicking::try::do_call
             at /checkout/src/libstd/rt.rs:59
             at /checkout/src/libstd/panicking.rs:480
  18: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  19: std::rt::lang_start_internal
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  20: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  21: main
  22: __libc_start_main
  23: _start
```

**Comment by florenzo-42** [comment]
Press `Z` right after startup:
```
➜  sodium git:(master) RUST_BACKTRACE=1 ./target/debug/sodium
Starting Sodium
First redraw of the screen
thread 'main' panicked at 'attempt to subtract with overflow', src/core/exec.rs:259:67
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: sodium::core::exec::<impl sodium::state::editor::Editor>::exec
             at src/core/exec.rs:259
  10: sodium::state::editor::Editor::init
             at src/state/editor.rs:321
  11: sodium::main
             at src/main.rs:24
  12: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  17: main
  18: __libc_start_main
  19: _start
```
Surprisingly other letters work fine...
